# for the demo, the galera nodes that are stretched need to send messages
# across the two overclouds.  we'll use ssh for this.   to make the demo
# simple, we're using root; in reality this can be a limited account.
# also to make it simple we're just generating one ssh key and using it
# on all the overcloud controller nodes.

- name: find and optionally generate the key for just one host
  block:
    - name: look for key
      stat: path=/root/.ssh/id_rsa
      register: ssh_keyfile
      become: true

    - name: generate key
      shell: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
      when: not ssh_keyfile.stat.exists
      become: true

    - name: read the key
      set_fact:
        id_rsa_pub: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        id_rsa: "{{ lookup('file', '/root/.ssh/id_rsa') }}"
      become: true

  run_once: true

- name: write public key
  copy:
    content: "{{ id_rsa_pub }}"
    dest: /root/.ssh/id_rsa.pub
    mode: 0644
    owner: root
    group: root
  become: true


- name: write private key
  copy:
    content: "{{ id_rsa }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
    owner: root
    group: root
  become: true

- name: add authorized key
  lineinfile:
    path: /root/.ssh/authorized_keys
    line: "{{ id_rsa_pub }}"