
vbmc_username: vbmc
vbmc_password: vbmc
vbmc_start_port: 6230

ntp_server: clock.corp.redhat.com


undercloud_inventoryname: undercloud-0

undercloud_network_cidr: 192.168.24.0/24

external_network_cidr: 10.0.10.0/24
internalapi_network_cidr: 10.0.20.0/24
storage_network_cidr: 10.0.30.0/24
storagemgmt_network_cidr: 10.0.40.0/24
tenant_network_cidr: 10.0.50.0/24



