stretch_network_vlan_name: vlan10
stretch_galera_imagename: stretch_galera

ntp_server: clock.corp.redhat.com

stretch_galera_master_inventoryname: s1controller-0
stretch_galera_follower_inventoryname: s2controller-0

# we were taking this from the original container,
# however when the two clusters join, one blows away the other ! :)
# so these have to be made the same
stretch_galera_root_password: galeraroot

stack1_undercloud_inventoryname: s1undercloud-0
stack2_undercloud_inventoryname: s2undercloud-0

# NOTE: we have some hardcoding in
# roles/deploy-overcloud/templates/naming_things.yaml.j2 and
# network-environemnt.yaml.j2 that is dependent on these specific
# settings should be genericized somehow
stack1_external_network_cidr: 10.0.10.0/24
stack1_internalapi_network_cidr: 10.0.20.0/24
stack1_storage_network_cidr: 10.0.30.0/24
stack1_storagemgmt_network_cidr: 10.0.40.0/24
stack1_tenant_network_cidr: 10.0.50.0/24

stack2_external_network_cidr: 10.1.10.0/24
stack2_internalapi_network_cidr: 10.1.20.0/24
stack2_storage_network_cidr: 10.1.30.0/24
stack2_storagemgmt_network_cidr: 10.1.40.0/24
stack2_tenant_network_cidr: 10.1.50.0/24



