- name: add haproxy cfg
  blockinfile:
    path: /var/lib/config-data/puppet-generated/haproxy/etc/haproxy/haproxy.cfg
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertbefore: "listen mysql"
    content: |
      listen mysql-stretch
        bind {{ stretch_galera_vip }}:3306 transparent
        option tcpka
        option httpchk
        stick on dst
        stick-table type ip size 1000
        timeout client 90m
        timeout server 90m

        {% for item in groups['galera_nodes'] %}
        server {{ hostvars[item]['pacemaker_node_name'] }} {{ hostvars[item]['transport_ip_number'] }}:{{ stretch_galera_listen_port }} {{ (item in groups[stack_name]) | ternary('', 'backup')}} check inter 1s on-marked-down shutdown-sessions port 9200
        {% endfor %}


  become: true

- name: restart haproxy via pcs
  shell: pcs resource restart haproxy-bundle
  become: true
  when:  "'pacemaker_control_nodes' in group_names"

