- name: set tripleo_heat_templates, puppet_tripleo fact
  set_fact:
    tripleo_heat_templates: "{{ working_dir }}/tripleo-patch/tripleo-heat-templates"
    puppet_tripleo: "{{ working_dir }}/tripleo-patch/puppet-tripleo"
  tags: always

- name: make patched tripleo area
  file:
    path: "{{ working_dir }}/tripleo-patch"
    state: directory

- name: make patched puppet-tripleo area
  file:
    path: "{{ puppet_tripleo }}"
    state: directory

- name: copy puppet-tripleo to local working dir
  shell: cp -Ru /usr/share/openstack-puppet/modules/tripleo {{ puppet_tripleo }}/

- name: copy t-h-t files
  shell: cp -Ru /usr/share/openstack-tripleo-heat-templates {{ working_dir }}/tripleo-patch/tripleo-heat-templates

- name: deploy new t-h-t, tripleo-puppet files
  copy:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
  with_items:
    - {
        src: "stretch_clustercheck.pp",
        dest: "{{ puppet_tripleo }}/tripleo/manifests/profile/pacemaker/stretch_clustercheck.pp"
    }
    - {
        src: "stretch_mysql_bundle.pp",
        dest: "{{ puppet_tripleo }}/tripleo/manifests/profile/pacemaker/database/stretch_mysql_bundle.pp"
    }
    - {
        src: "stretch_clustercheck.yaml",
        dest: "{{ tripleo_heat_templates }}/docker/services/pacemaker/stretch_clustercheck.yaml"
    }
    - {
        src: "stretch_mysql.yaml",
        dest: "{{ tripleo_heat_templates }}/docker/services/pacemaker/database/stretch_mysql.yaml"
    }
    - {
        src: "docker_stretch_galera.yaml",
        dest: "{{ tripleo_heat_templates }}/environments/docker-stretch-galera.yaml"
    }


- name: patch t-h-t
  patch:
      src: t-h-t.patch
      basedir: "{{ tripleo_heat_templates }}"
      strip: 1

- name: regenerate endpoint map
  shell: ./build_endpoint_map.py
  args:
    chdir: "{{ tripleo_heat_templates }}/network/endpoints"

- name: patch puppet_tripleo
  patch:
      src: puppet-tripleo.patch
      basedir: "{{ puppet_tripleo }}/tripleo/"
      strip: 1

- name: run upload-puppet-modules
  shell: |
      source ~/stackrc
      upload-puppet-modules -d {{ puppet_tripleo }}


