- name: set tripleo_heat_templates, puppet_tripleo fact
  set_fact:
    tripleo_heat_templates: "{{ working_dir }}/tripleo-patch/tripleo-heat-templates"
    puppet_tripleo: "{{ working_dir }}/tripleo-patch/puppet-tripleo"
  tags: always

- name: make patched tripleo area
  file:
    path: "{{ working_dir }}/tripleo-patch"
    state: directory

- name: erase existing patched tripleo area
  shell: rm -fr {{ working_dir }}/tripleo-patch

- name: make patched puppet-tripleo area
  file:
    path: "{{ puppet_tripleo }}"
    state: directory

- name: copy puppet-tripleo to local working dir
  shell: cp -R /usr/share/openstack-puppet/modules/tripleo {{ puppet_tripleo }}/

- name: copy t-h-t files
  shell: cp -R /usr/share/openstack-tripleo-heat-templates {{ working_dir }}/tripleo-patch/tripleo-heat-templates

- name: copy t-h-t.patch since ansible patch does not support -F
  copy:
    src: t-h-t.{{ release_name }}.patch
    dest: /home/stack/t-h-t.patch

- name: make sure patch is installed
  yum:
      name: patch
      state: installed
  become: yes

- name: patch t-h-t
  shell: patch -F20 -p1 < /home/stack/t-h-t.patch
  args:
    chdir: "{{ tripleo_heat_templates }}"

- name: regenerate endpoint map
  shell: ./build_endpoint_map.py
  args:
    chdir: "{{ tripleo_heat_templates }}/network/endpoints"

- name: copy puppet_tripleo patch since ansible patch does not support -F
  copy:
     src: puppet-tripleo.{{ release_name }}.patch
     dest: /home/stack/puppet-tripleo.patch

- name: patch puppet_tripleo
  shell: patch -F20 -p1 < /home/stack/puppet-tripleo.patch
  args:
    chdir: "{{ puppet_tripleo }}/tripleo/"

- name: run upload-puppet-modules
  shell: |
      source ~/stackrc
      upload-puppet-modules -d {{ puppet_tripleo }}


