overcloud_dns_servers:
  - "10.16.36.29"
  - "10.11.5.19"
  - "10.5.30.160"


# this defaults to External in the roles_data.yaml:
# we are changing it to ControlPlane.
# background:
# https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/custom_roles.html

# default_route_networks_controller: ControlPlane

# compute is not normally defined but we are setting it here.
# default_route_networks_compute: ControlPlane

vbmc_username: vbmc
vbmc_password: vbmc

# should be called "working_undercloud_dir"
working_dir: "/home/stack/"

release_numeric_versions: {"queens": 13, "pike": 12}

undercloud_management_ip: "{{ undercloud_network_cidr|nthhost(1) }}"

compute_scale: 1

control_scale: 3

stack1_external_network_cidr: 10.0.10.0/24
stack1_internalapi_network_cidr: 10.0.20.0/24
stack1_storage_network_cidr: 10.0.30.0/24
stack1_storagemgmt_network_cidr: 10.0.40.0/24
stack1_tenant_network_cidr: 10.0.50.0/24

stack2_external_network_cidr: 10.1.10.0/24
stack2_internalapi_network_cidr: 10.1.20.0/24
stack2_storage_network_cidr: 10.1.30.0/24
stack2_storagemgmt_network_cidr: 10.1.40.0/24
stack2_tenant_network_cidr: 10.1.50.0/24


