overcloud_dns_servers:
  - "10.16.36.29"
  - "10.11.5.19"
  - "10.5.30.160"


# this defaults to External in the roles_data.yaml:
# we are changing it to ControlPlane.
# background:
# https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/custom_roles.html

# default_route_networks_controller: ControlPlane

# compute is not normally defined but we are setting it here.
# default_route_networks_compute: ControlPlane


# should be called "working_undercloud_dir"
working_dir: "/home/stack/"

release_numeric_versions: {"15-trunk": 15, "15": 15, "14": 14, "13": 13, "stein": 15, "rocky": 14, "queens": 13, "pike": 12}

heat_template_versions: {"15-trunk": "rocky", "15": "rocky", "14": "rocky", "13": "queens", "stein": "rocky", "rocky": "rocky", "queens": "queens", "pike": "ocata"}
rhos_or_rdo_lookup: {"15-trunk": "rhos", "15": "rhos", "14": "rhos", "13": "rhos", "stein": "rdo", "rocky": "rdo", "queens": "rdo", "pike": "rdo"}

undercloud_management_ip: "{{ undercloud_network_cidr|nthhost(1) }}"

compute_scale: 1

control_scale: 3


