overcloud_dns_servers:
  - "10.16.36.29"
  - "10.11.5.19"
  - "10.5.30.160"

vbmc_username: vbmc
vbmc_password: vbmc

# should be called "working_undercloud_dir"
working_dir: "/home/stack/"

release_numeric_versions: {"queens": 13, "pike": 12}

undercloud_management_ip: "{{ undercloud_network_cidr|nthhost(1) }}"

compute_scale: 1

control_scale: 3

network_environment_args:
  # mostly from https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/network_isolation.html
  # as well as https://github.com/openstack/tripleo-quickstart-extras/blob/master/roles/overcloud-prep-config/defaults/main.yml#L15

  ExternalNetCidr: "{{ external_network_cidr }}"
  ExternalAllocationPools: >
    [{'start': '{{ external_network_cidr|nthhost(10) }}',
    'end': '{{ external_network_cidr|nthhost(250) }}'}]

  InternalApiNetCidr: "{{ internalapi_network_cidr }}"
  StorageNetCidr: "{{ storage_network_cidr }}"
  StorageMgmtNetCidr: "{{ storagemgmt_network_cidr }}"
  TenantNetCidr: "{{ tenant_network_cidr }}"

  InternalApiAllocationPools: >
    [{
      'start': '{{ external_network_cidr|nthhost(10) }}',
      'end': '{{ external_network_cidr|nthhost(200) }}',
    }]
  StorageAllocationPools: >
    [{
      'start': '{{ storage_network_cidr|nthhost(10) }}',
      'end': '{{ storage_network_cidr|nthhost(200) }}',
    }]
  StorageMgmtAllocationPools: >
    [{
      'start': '{{ storagemgmt_network_cidr|nthhost(10) }}',
      'end': '{{ storagemgmt_network_cidr|nthhost(200) }}',
    }]
  TenantAllocationPools: >
    [{
      'start': '{{ tenant_network_cidr|nthhost(10) }}',
      'end': '{{ tenant_network_cidr|nthhost(200) }}',
    }]

  NeutronExternalNetworkBridge: ""
  ExternalInterfaceDefaultRoute: "{{ external_network_cidr|nthhost(1) }}"
  ControlPlaneSubnetCidr: "{{ undercloud_network_cidr|ipaddr('prefix') }}"
  ControlPlaneDefaultRoute: "{{ undercloud_management_ip }}"
  EC2MetadataIp: "{{ undercloud_management_ip }}"
  DnsServers: "{{ overcloud_dns_servers }}"



  # When we have two overclouds, we need to SSH around and we will see these
  # names in our command prompts and you are really going to want to see which
  # stack this is, e.g. "stack1-overcloud-controller-0" and not "overcloud-
  # controller-0", in those names.
  HostnameMap:
    overcloud-controller-0: "{{ rh_stack_name }}-overcloud-controller-0"
    overcloud-controller-1: "{{ rh_stack_name }}-overcloud-controller-1"
    overcloud-controller-2: "{{ rh_stack_name }}-overcloud-controller-2"
    overcloud-compute-0: "{{ rh_stack_name }}-overcloud-compute-0"
    overcloud-novacompute-0: "{{ rh_stack_name }}-overcloud-compute-0"

  # The overclouds are going to share the same Keystone database.  So lets
  # set up for two different regions, e.g. region_stack1 and region_stack2.
  # at the moment it seems like the OSP12 overclouds default to not using
  # keystone endpoints and instead have service IPs hardcoded, but using
  # endpoint discovery w/ regions is cooler.
  # Unfortunately, this option appears to work only sporadically as
  # far as being correctly populated into .conf files, some
  # OSP versions seem to honor it and others ignore it, so we have to
  # populate .conf files with it after the fact regardless
  KeystoneRegion: "region_{{ rh_stack_name }}"

  # since we are sharing the same keystone, the services on both
  # overclouds need to use the same passwords.  clearly this would have
  # to be integrated into the "make a bunch of passwords" thing :)
  ManilaPassword: "Manila_password"
  NeutronPassword: "Neutron_password"
  GlancePassword: "Glance_password"
  HeatPassword: "Heat_password"
  AdminPassword: "Admin_password"
  IronicPassword: "Ironic_password"
  HeatStackDomainAdminPassword: "HeatStackDomainAdmin_password"
  ZaqarPassword: "Zaqar_password"
  GnocchiPassword: "Gnocchi_password"
  CeilometerPassword: "Ceilometer_password"
  CinderPassword: "Cinder_password"
  NovaPassword: "Nova_password"
  MistralPassword: "Mistral_password"
  AodhPassword: "Aodh_password"
  SwiftPassword: "Swift_password"
  BarbicanPassword: "Barbican_password"
  SaharaPassword: "Sahara_password"
