# for the demo, the galera nodes that are stretched need to send messages
# across the two overclouds.  we'll use ssh for this.   to make the demo
# simple, we're using root; in reality this can be a limited account.
# also to make it simple we're just generating one ssh key and using it
# on all the overcloud controller nodes.

- name: find and optionally generate the key for just one host
  block:
    - name: look for key
      stat: path=/tmp/id_rsa_overcloud
      register: ssh_keyfile

    - name: generate key
      shell: ssh-keygen -t rsa -f /tmp/id_rsa_overcloud -N ''
      when: not ssh_keyfile.stat.exists

    - name: read the public key
      shell: cat /tmp/id_rsa_overcloud.pub
      register: idrsapub

    - name: read the private key
      shell: cat /tmp/id_rsa_overcloud
      register: idrsa

    - name: store keys
      set_fact:
        id_rsa_pub: "{{ idrsapub.stdout }}"
        id_rsa: "{{ idrsa.stdout }}"

  run_once: true

- name: write public key
  copy:
    content: "{{ id_rsa_pub }}"
    dest: /root/.ssh/id_rsa.pub
    mode: 0644
    owner: root
    group: root
  become: true


- name: write private key
  copy:
    content: "{{ id_rsa }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
    owner: root
    group: root
  become: true

- name: add authorized key
  lineinfile:
    create: yes
    owner: root
    group: root
    mode: 0600
    path: /root/.ssh/authorized_keys
    line: "{{ id_rsa_pub }}"
  become: true

