- name: Create network environment file for network isolation
  template:
    src: "network-environment.yaml.j2"
    dest: "{{ working_dir }}/network-environment.yaml"
    mode: 0644

- name: create two-nics-vlans dir
  file:
    path: "{{ working_dir }}/two-nics-vlans"
    state: directory

- name: more templates
  template:
    src: "two-nics-vlans/{{ item }}.j2"
    dest: "{{ working_dir }}/two-nics-vlans/{{ item }}"
    mode: 0644
  with-items: ["controller.yaml", "compute.yaml"]
