- name: Create network environment file for network isolation
  template:
    src: "network-environment.yaml.j2"
    dest: "{{ working_dir }}/network-environment.yaml"
    mode: 0644

- name: generate custom roles
  shell: |
      source {{ working_dir }}/stackrc
      openstack overcloud roles generate -o {{ working_dir }}/roles_data.yaml Controller Compute


- name: create two-nics-vlans dir
  file:
    path: "{{ working_dir }}/two-nics-vlans"
    state: directory

- name: more templates
  template:
    src: "two-nics-vlans/{{ item }}.j2"
    dest: "{{ working_dir }}/two-nics-vlans/{{ item }}"
    mode: 0644
  with_items: ["controller.yaml", "compute.yaml"]

- name: copy naming file
  template:
    src: naming_things.yaml.j2
    dest: "{{ working_dir }}/naming_things.yaml"

- name: transfer overcloud script
  template:
    src: deploy_overcloud.sh.j2
    dest: "{{ working_dir }}/deploy_overcloud.sh"
    mode: 0755


