- name: deploy!
  shell: |
      source {{ working_dir }}/stackrc;
      {{ working_dir }}/deploy_overcloud.sh &> overcloud_deploy.log

- name: check that it passed
  shell:
      echo $(tail -50 {{ working_dir }}/overcloud_deploy.log | grep -vi warning | tail -1)
  register: deploy_result

- name: check passing
  fail:
    msg: "didn't see success message at end of deploy log"
  when: "'Overcloud Deployed' not in deploy_result.stdout"


