- name: remove existing nodes
  shell: |
      source {{ working_dir }}/stackrc
      for item in $( openstack baremetal node list --format value -c UUID ); do openstack baremetal node delete $item; done
  retries: 5
  delay: 10

- name: register hosts to instack and configure boot
  shell: |
      set -eo pipefail
      source {{ working_dir }}/stackrc

      {% if release_numeric_version < 13 %}
      openstack baremetal import --json {{ working_dir }}/instackenv.json
      openstack baremetal configure boot
      {% else %}
      openstack overcloud node import --instance-boot-option=local {{ working_dir }}/instackenv.json
      {% endif %}

- name: start node introspection
  shell: |
      source {{ working_dir }}/stackrc
      {% if release_numeric_version < 13 %}
      openstack baremetal introspection bulk start
      {% else %}
      openstack overcloud node introspect --provide --all-manageable
      {% endif %}
  register: bulk_intro_result
  poll: 50
  async: 1000
  retries: 20
  delay: 90
  ignore_errors: no

