# this is the workaround pre https://review.openstack.org/#/c/642374/
- name: run zaqar workaround #1
  shell: |
    cp cm-local-ca.pem cm-local-ca.pem.savd
    cp undercloud-cacert.pem cm-local-ca.pem
  become: yes
  args:
    chdir: /etc/pki/ca-trust/source/anchors

# this is the workaround post https://review.openstack.org/#/c/642374/1
- name: run zaqar workaround #2
  lineinfile:
    line: 'export OS_CACERT="/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem"'
    path: "{{ working_dir }}/stackrc"

- name: remove existing nodes
  shell: |
      source {{ working_dir }}/stackrc
      for item in $( openstack baremetal node list --format value -c UUID ); do openstack baremetal node delete $item; done
  retries: 5
  delay: 10

- name: register hosts to instack and configure boot
  shell: |
      set -eo pipefail
      source {{ working_dir }}/stackrc

      {% if release_numeric_version | int < 13 %}
      openstack baremetal import --json {{ working_dir }}/instackenv.json
      openstack baremetal configure boot
      {% else %}
      openstack overcloud node import --instance-boot-option=local {{ working_dir }}/instackenv.json
      {% endif %}

- name: start node introspection
  shell: |
      source {{ working_dir }}/stackrc
      {% if release_numeric_version | int < 13 %}
      openstack baremetal introspection bulk start
      {% else %}
      openstack overcloud node introspect --provide --all-manageable
      {% endif %}
  register: bulk_intro_result
  poll: 50
  async: 1000
  retries: 20
  delay: 90
  ignore_errors: no

