- name: config
  include_vars: "{{ playbook_dir }}/../config.yml"
  tags: always

- name: get hypervisor-generated ssh key
  set_fact:
    id_rsa_pub: "{{ hostvars['hypervisor']['id_rsa_pub'] }}"
    id_rsa: "{{ hostvars['hypervisor']['id_rsa'] }}"
  tags: always

- name: set release number, hypervisor management address
  set_fact:
    release_numeric_version: "{{ release_numeric_versions[release_name] }}"
    management_ipv4_address: "{{ hostvars['hypervisor']['ansible_default_ipv4']['address'] }}"
  tags: always

- name: setup stack1-local variables
  set_fact:
    external_network_cidr: "{{ stack1_external_network_cidr }}"
    internalapi_network_cidr: "{{ stack1_internalapi_network_cidr }}"
    storage_network_cidr: "{{ stack1_storage_network_cidr }}"
    storagemgmt_network_cidr: "{{ stack1_storagemgmt_network_cidr }}"
    tenant_network_cidr: "{{ stack1_tenant_network_cidr }}"
  when: "rh_stack_name == 'stack1'"
  tags: always

- name: setup stack2-local variables
  set_fact:
    external_network_cidr: "{{ stack2_external_network_cidr }}"
    internalapi_network_cidr: "{{ stack2_internalapi_network_cidr }}"
    storage_network_cidr: "{{ stack2_storage_network_cidr }}"
    storagemgmt_network_cidr: "{{ stack2_storagemgmt_network_cidr }}"
    tenant_network_cidr: "{{ stack2_tenant_network_cidr }}"
  when: "rh_stack_name == 'stack2'"
  tags: always

- name: remove existing overclouds
  import_tasks: undeploy_overcloud.yml
  tags: run_deploy_overcloud

- name: set up vlan
  import_tasks: setup_vlan.yml
  tags: setup_vlan

- name: tune undercloud
  import_tasks: tune_undercloud.yml
  tags: tune_undercloud

- name: Configure vbmc
  include_role:
    name: vbmc
  vars:
    vbmc_nodes: "{{ groups.get('overcloud_nodes', []) }}"
    vbmc_host: undercloud
  tags:
    - install_vbmc
    - create_instackenv

# creating the instackenv requires some of the vbmc info.
# the infrared vbmc role currently is hardcoded to remove
# and re-add the vbmc nodes for each machine every time,
# but we only need to create instackenv once so it's not worth
# trying to make this more efficient
- name: create instackenv
  import_tasks: create_instackenv.yml
  tags: create_instackenv

- name: build heat config
  import_tasks: build_heat_config.yml
  tags: build_heat_config

- name: introspect nodes
  import_tasks: introspect_nodes.yml
  tags: introspect_nodes

- name: create flavors
  import_tasks: create_flavors.yml
  tags: create_flavors

- name: setup container stuff
  import_tasks: setup_containers.yml
  tags: prepare_containers

- name: create modified galera container
  import_tasks: modify_galera_image.yml
  tags: prepare_containers,make_galera_image

- name: deploy overcloud
  import_tasks: deploy_overcloud.yml
  tags: run_deploy_overcloud
