- name: remove existing ironic nodes 
  shell: |
      source {{ working_dir }}/stackrc
      for item in $( openstack baremetal node list --format value -c UUID ); do openstack baremetal node delete $item; done
  retries: 5
  delay: 10


