- name: config
  include_vars: "{{ playbook_dir }}/../config.yml"

- name: get hypervisor-generated ssh key
  set_fact:
    id_rsa_pub: "{{ hostvars['hypervisor']['id_rsa_pub'] }}"
    id_rsa: "{{ hostvars['hypervisor']['id_rsa'] }}"

- name: set release number, hypervisor management address
  set_fact:
    release_numeric_version: "{{ release_numeric_versions[release_name] }}"
    management_ipv4_address: "{{ hostvars['hypervisor']['ansible_default_ipv4']['address'] }}"

- name: set stack1 name
  set_fact:
    rh_stack_name: "stack1"
  when: "rh_stack_name is not defined and 'stack1' in group_names"

- name: set stack2 name
  set_fact:
    rh_stack_name: "stack2"
  when: "rh_stack_name is not defined and 'stack2' in group_names"

- name: setup stack1-local variables
  set_fact:
    external_network_cidr: "{{ stack1_external_network_cidr }}"
    internalapi_network_cidr: "{{ stack1_internalapi_network_cidr }}"
    storage_network_cidr: "{{ stack1_storage_network_cidr }}"
    storagemgmt_network_cidr: "{{ stack1_storagemgmt_network_cidr }}"
    tenant_network_cidr: "{{ stack1_tenant_network_cidr }}"
    undercloud_network_cidr: "{{ stack1_undercloud_network_cidr }}"
  when: "rh_stack_name == 'stack1'"

- name: setup stack2-local variables
  set_fact:
    external_network_cidr: "{{ stack2_external_network_cidr }}"
    internalapi_network_cidr: "{{ stack2_internalapi_network_cidr }}"
    storage_network_cidr: "{{ stack2_storage_network_cidr }}"
    storagemgmt_network_cidr: "{{ stack2_storagemgmt_network_cidr }}"
    tenant_network_cidr: "{{ stack2_tenant_network_cidr }}"
    undercloud_network_cidr: "{{ stack2_undercloud_network_cidr }}"
  when: "rh_stack_name == 'stack2'"


