- name: does overcloud_containers.yaml (OSP<=13) already exist?
  stat:
    path: "{{ working_dir }}/overcloud_containers.yaml"
  register: overcloud_containers
  when: release_numeric_version | int <= 13

- name: does containers-default-parameters.yaml (OSP>13) already exist?
  stat:
    path: "{{ working_dir }}/containers-default-parameters.yaml"
  register: overcloud_containers
  when: release_numeric_version | int > 13

# see https://github.com/openstack/tripleo-quickstart-extras/commit/b3794ff03ab841bbbc15a339e35a7ec02b193111#diff-51f6a4c98274d504643778b3633252cf
# note containers-prepare-parameter.yaml must be generated, either by us
# or by undercloud install (comes from undercloud.conf)
- name: setup docker images, post-queens style
  when:
    - release_numeric_version | int > 13
    - not overcloud_containers.stat.exists | bool
  block:
    - name: "create container configs, step 1"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack tripleo container image prepare default
          --local-push-destination
          --output-env-file {{ working_dir }}/tripleo-config-generated-env-files/containers-prepare-parameter.yaml

    - name: "create container configs, step 2 download"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack tripleo container image prepare
          --output-env-file {{ working_dir }}/containers-default-parameters.yaml
          -e {{ working_dir }}/tripleo-config-generated-env-files/containers-prepare-parameter.yaml
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0

- name: install docker images, queens and previous style
  when:
    - release_numeric_version | int <= 13
    - not overcloud_containers.stat.exists | bool
  block:
    - name: work around https://bugs.launchpad.net/tripleo/+bug/1727347
      stat:
        path: "{{ working_dir }}/.tripleo/environments"
      register: env_file

    - name: remove .tripleo environments directory if present
      shell: mv .tripleo/environments .tripleo/environments_save
      args:
        chdir: "{{ working_dir }}/stackrc"
      when: env_file.stat.exists | bool


    - name: create container configs
      shell: >
          source {{ working_dir }}/stackrc;
          openstack overcloud container image prepare
          --namespace docker.io/tripleo{{ container_namespace }}
          --tag {{ container_tag }}
          --tag-from-label rdo_version
          --push-destination {{ undercloud_management_ip }}:8787
          --output-env-file {{ working_dir }}/docker_registry.yaml
          --output-images-file overcloud_containers.yaml

    - name: restore .tripleo environments directory if present
      shell: mv .tripleo/environments_save .tripleo/environments
      args:
        chdir: "{{ working_dir }}/stackrc"
      when: env_file.stat.exists | bool

      # something weird here when working manually:
      # https://bugzilla.redhat.com/show_bug.cgi?id=1646787
      # sudo bash
      # [root@undercloud stack]# exec su -l stack
      # then it works ?
      # OK - when undercloud has been installed, stack user needs to log
      # out and log in again in order to push to docker

    - name: transfer docker images
      shell: >
          source {{ working_dir }}/stackrc;
          openstack overcloud container image upload --verbose
          --config-file overcloud_containers.yaml
      retries: 3
      delay: 5
      register: result
      until: result.rc == 0
