- name: config
  include_vars: "{{ playbook_dir }}/../config.yml"

- name: get hypervisor-generated ssh key
  set_fact:
    id_rsa_pub: "{{ hostvars['hypervisor']['id_rsa_pub'] }}"
    id_rsa: "{{ hostvars['hypervisor']['id_rsa'] }}"

- name: set other facts
  set_fact:
    release_numeric_version: "{{ release_numeric_versions[release_name] }}"
    management_ipv4_address: "{{ hostvars['hypervisor']['ansible_default_ipv4']['address'] }}"
    overcloud_nodes: "{{ groups.get('overcloud_nodes', []) }}"
    rhos_or_rdo: "{{ rhos_or_rdo_lookup[release_name] }}"

    # this was set to the local directory in stretch_galera, can be made
    # dynamic again if we need to modify templates
    # tripleo_heat_templates: "{{ working_dir }}/tripleo-patch/tripleo-heat-templates"

    tripleo_heat_templates: "/usr/share/openstack-tripleo-heat-templates/"
