- name: does containers-default-parameters.yaml already exist?
  stat:
    path: "{{ working_dir }}/containers-default-parameters.yaml"
  register: overcloud_containers

- name: does containers-prepare-parameter.yaml already exist?
  stat:
    path: "{{ working_dir }}/containers-prepare-parameter.yaml"
  register: containers_prepare_parameter

# see https://github.com/openstack/tripleo-quickstart-extras/commit/b3794ff03ab841bbbc15a339e35a7ec02b193111#diff-51f6a4c98274d504643778b3633252cf
# note containers-prepare-parameter.yaml must be generated, either by us
# or by undercloud install (comes from undercloud.conf)
#
- name: setup docker images, rocky and post
  when:
    - release_numeric_version | int >= 14
    - not overcloud_containers.stat.exists | bool
  block:
    - name: "create container configs, step 1"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack tripleo container image prepare default
          --output-env-file {{ working_dir }}/containers-prepare-parameter.yaml
      when: not containers_prepare_parameter.stat.exists | bool

    - name: "create container configs, step 2 create download config"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack tripleo container image prepare
          --output-env-file {{ working_dir }}/containers-default-parameters.yaml
          -e {{ working_dir }}/containers-prepare-parameter.yaml
      retries: 10
      delay: 30
      register: result
      until: result.rc == 0

- name: setup docker images, queens and previous style
  when:
    - release_numeric_version | int <= 13
    - not overcloud_containers.stat.exists | bool
  block:
    - name: work around https://bugs.launchpad.net/tripleo/+bug/1727347
      stat:
        path: "{{ working_dir }}/.tripleo/environments"
      register: env_file

    - name: remove .tripleo environments directory if present
      shell: mv .tripleo/environments .tripleo/environments_save
      args:
        chdir: "{{ working_dir }}/stackrc"
      when: env_file.stat.exists | bool


    - name: "create rdo container configs, step 1"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack overcloud container image prepare
          --namespace docker.io/tripleo{{ rdo_container_namespace }}
          --tag {{ container_tag }}
          --tag-from-label rdo_version
          --output-env-file {{ working_dir }}/docker_registry.yaml
          --output-images-file overcloud_containers.yaml
      when: rhos_or_rdo == "rdo"

    - name: "create rhos container configs, step 1"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack overcloud container image prepare
          --output-env-file {{ working_dir }}/containers-prepare-parameter.yaml
      when: rhos_or_rdo == "rhos"

    - name: restore .tripleo environments directory if present
      shell: mv .tripleo/environments_save .tripleo/environments
      args:
        chdir: "{{ working_dir }}/stackrc"
      when: env_file.stat.exists | bool

    - name: "create container configs, step 2 download config"
      shell: >
          source {{ working_dir }}/stackrc;
          openstack overcloud container image prepare
          --output-env-file {{ working_dir }}/containers-default-parameters.yaml
          -e {{ working_dir }}/containers-prepare-parameter.yaml
      retries: 10
      delay: 30
      register: result
      until: result.rc == 0

