- name:  get existing overclouds
  shell: |
      source {{ working_dir }}/stackrc;
      openstack stack list -c ID --format value
  register: stack_names

- name: remove existing overclouds
  shell: | 
      source {{ working_dir }}/stackrc;
      openstack stack delete {{ item }} --wait --yes
  with_items: "{{ stack_names.stdout_lines }}"

- name: remove logfile since we check it for success
  shell: |
      rm -f {{ working_dir }}/overcloud_deploy.log
 
