
- name: set region names
  lineinfile:
    path: /var/lib/config-data/puppet-generated/{{ item }}
    insertafter: ^[DEFAULT]
    regexp: ^region_name=
    line: region_name=region_{{ stack_name }}
  with_items:
    - heat_api/etc/heat/heat.conf
    - nova_placement/etc/nova/nova.conf
    - heat/etc/heat/heat.conf
    - nova/etc/nova/nova.conf
    - glance_api/etc/glance/glance-api.conf
    - glance_api/etc/glance/glance-cache.conf
    - cinder/etc/cinder/cinder.conf
    - heat_api_cfn/etc/heat/heat.conf
    - neutron/etc/neutron/neutron.conf

- name: set region names
  lineinfile:
    path: /var/lib/config-data/puppet-generated/{{ item }}
    insertafter: ^[DEFAULT]
    regexp: ^os_region_name=
    line: os_region_name=region_{{ stack_name }}
  with_items:
    - heat_api/etc/heat/heat.conf
    - nova_placement/etc/nova/nova.conf
    - heat/etc/heat/heat.conf
    - nova/etc/nova/nova.conf
    - glance_api/etc/glance/glance-api.conf
    - glance_api/etc/glance/glance-cache.conf
    - cinder/etc/cinder/cinder.conf
    - heat_api_cfn/etc/heat/heat.conf
    - neutron/etc/neutron/neutron.conf


- name: change DB url in keystone.conf
  lineinfile:
    path: /var/lib/config-data/puppet-generated/keystone/etc/keystone/keystone.conf
    regexp: ^connection=
    # TODO: need a new cnf file with an appropriate bind_address for this to work
    #line: connection=mysql+pymysql://keystone:stretch_keystone@{{ stretch_galera_vip }}/keystone?read_default_group=tripleo&read_default_file=/etc/my.cnf.d/tripleo.cnf
    line: connection=mysql+pymysql://keystone:stretch_keystone@{{ stretch_galera_vip }}/keystone
  become: true

- name: restart services!
  shell: docker restart {{ item }}
  become: true
  with_items:
    - keystone
    - nova_conductor
    - nova_metadata
    - nova_api
    - glance_api
    - cinder_api
    - cinder_scheduler
    - neutron_metadata_agent
    - neutron_ovs_agent
    - neutron_api
    - heat_engine