
- name: set region names
  ini_file:
    path: /var/lib/config-data/puppet-generated/{{ item['filename'] }}
    section: "{{ item['section'] }}"
    option: "region_name"
    value: "region_{{ stack_name }}"
    backup: yes
  become: true
  with_items:
    - {"filename": "nova/etc/nova/nova.conf", "section": "keystone"}
    - {"filename": "nova/etc/nova/nova.conf", "section": "keystone_authtoken"}
# etc
#

- name: restart services!
  shell: docker restart {{ item }}
  become: true
  with_items:
#    - keystone
    - memcached
    - nova_api
#    - nova_conductor
#    - nova_metadata
#    - glance_api
#    - cinder_api
#    - cinder_scheduler
#    - neutron_metadata_agent
#    - neutron_ovs_agent
#    - neutron_api
#    - heat_engine
