

- name: change DB url in keystone.conf
  lineinfile:
    path: /var/lib/config-data/puppet-generated/keystone/etc/keystone/keystone.conf
    regexp: ^connection=
    # TODO: need a new cnf file with an appropriate bind_address for this to work
    #line: connection=mysql+pymysql://keystone:stretch_keystone@{{ stretch_galera_vip }}/keystone?read_default_group=tripleo&read_default_file=/etc/my.cnf.d/tripleo.cnf
    line: connection=mysql+pymysql://keystone:stretch_keystone@{{ stretch_galera_vip }}/keystone
  become: true

- name: restart keystone!
  shell: docker restart keystone
  become: true
