
# special trick to get a list, so we can use join() and avoid trailing comma
- name: get gcomm host entries
  set_fact:
    gcomm_entry="{{ hostvars[item]['external_hostname'] }}"
    hostmap_entry="{{ hostvars[item]['pacemaker_node_name'] }}:{{ hostvars[item]['external_hostname'] }}"
  register: all_hosts_result
  with_items: "{{ groups['galera_nodes'] }}"

- name: create gcomm address, cluster_host_map
  set_fact:
    gcomm_address: "gcomm://{{ all_hosts_result.results | map(attribute='ansible_facts.gcomm_entry') | join(',') }}"
    cluster_host_map: "{{ all_hosts_result.results | map(attribute='ansible_facts.hostmap_entry') | join(';') }}"



# these next two maps we can do the easy way because we don't care about trailing semicolon
- name: create stack1 remote_node_map from stack2 nodes
  set_fact:
    remote_node_map: "{{ remote_node_map | default('') }}{{ hostvars[item]['pacemaker_node_name'] }}:root@{{ hostvars[item]['external_hostname'] }};"
  with_items: "{{ groups['galera_nodes'] | intersect(groups['stack2']) }}"
  when: "'stack1' in group_names"

- name: create stack2 remote_node_map from stack1 nodes
  set_fact:
    remote_node_map: "{{ remote_node_map | default('') }}{{ hostvars[item]['pacemaker_node_name'] }}:root@{{ hostvars[item]['external_hostname'] }};"
  with_items: "{{ groups['galera_nodes'] | intersect(groups['stack1']) }}"
  when: "'stack2' in group_names"

- name: set master overcloud weight
  set_fact:
    pc_weight: "2"
  when: "'stack1' in group_names"

- name: set follower overcloud weight
  set_fact:
    pc_weight: "1"
  when: "'stack2' in group_names"

