- name: pull config variables into environment
  include_vars: "{{ playbook_dir }}/../config.yml"
  tags: always

- name: set stack1 name
  set_fact:
    stack_name: "stack1"
  when: "'stack1' in group_names"

- name: set stack2 name
  set_fact:
    stack_name: "stack2"
  when: "'stack2' in group_names"


- name: get galera-node specific information
  when: "'galera_nodes' in group_names"
  block:

    - name: Get transport IP
      shell: /sbin/ip -4 addr show {{ stretch_network_vlan_name }} | grep "inet\b" | awk '{print $2}' | cut -d/ -f1
      register: transport_ip_number_cmd

    - name: set transport IP fact
      set_fact:
         transport_ip_number: '{{ transport_ip_number_cmd.stdout_lines[0] }}'

    - name: get docker container name
      shell: "docker ps --all | grep stretch-galera-bundle-docker | awk -F' ' '{print $NF}' | grep -e '^stretch-galera'"
      register: docker_ps_cmd
      become: true

    - name: set docker container name fact
      set_fact:
        galera_docker_container_name: "{{ docker_ps_cmd.stdout }}"

    - name: get galera DB root password
      shell: "crudini --get <(cat /var/lib/config-data/puppet-generated/stretch_mysql/root/.my.cnf) client password | xargs echo"
      args:
        executable: /bin/bash
      register: stretch_galera_pw_cmd
      become: true

    - name: set galera DB root password fact
      set_fact:
        stretch_galera_root_password: "{{ stretch_galera_pw_cmd.stdout }}"

    - name: set local galera login fact
      set_fact:
        stretch_galera_local_login: '-u root --password="{{ stretch_galera_root_password }}" -h {{ transport_ip_number }}'

    - name: set master /follower login facts
      set_fact:
          stretch_galera_master_login: "{{ hostvars[stretch_galera_master_inventoryname]['stretch_galera_local_login'] }}"
          stretch_galera_follower_login: "{{ hostvars[stretch_galera_follower_inventoryname]['stretch_galera_local_login'] }}"

- name: get external hostname for /etc/hosts
  shell: hostname
  register: hostname_cmd

- name: set external hostname for /etc/hosts
  set_fact:
    external_hostname: "{{ hostname_cmd.stdout_lines[0] }}.external"

- name: get pacemaker nodes
  block:
  - name: get pacemaker node name
    shell: /usr/sbin/crm_node -n
    register: get_nodename_cmd

  - name: set pacemaker node name fact
    set_fact:
      pacemaker_node_name: '{{ get_nodename_cmd.stdout }}'
  when: "'stack1_controller' in group_names or 'stack2_controller' in group_names"
