---
# note: this is very simplified from infrareds.   brute-force install pip
# from the get-pip.py script, install virtualbmc from pip. don't attempt
# to mess with python packages or easy install.

- name: Install packages
  become: true
  package:
      name:
        - ipmitool
        - gcc
        - libvirt
        - libvirt-devel
      state: latest
      disable_gpg_check: yes

- name: install pip
  become: true
  script: |
    mkdir -p /usr/local/src
    cd /usr/local/src
    curl -L -O https://bootstrap.pypa.io/get-pip.py
    /usr/bin/python ./get-pip.py  --prefix /usr

- name: Install python-virtualbmc with pip
  become: true
  pip:
      name: virtualbmc
      state: latest
