---
- name: Install packages required for 'pxe_ipmitool' ironic's driver on RedHat based distros
  become: true
  package:
      name:
        - python3-setuptools  # TODO: RDO wants python-setuptools
        - ipmitool
      state: latest
      disable_gpg_check: yes

# TODO: rhel8 thing
- name: hard-create python 3.6 easy install location, total hack
  file:
    path: "/usr/local/lib/python3.6"
    state: directory
  become: true

- name: Install python-virtualbmc from repo's
  become: true
  yum:
 # package:
      name: python-virtualbmc
      state: latest
      disable_gpg_check: yes
  ignore_errors: yes
  register: virtualbmc_install_result

- block:
    - name: Install packages required for python-virtualbmc pip package
      become: true
      package:
          name:
            - gcc
            - libvirt
            - libvirt-devel
          state: latest
          disable_gpg_check: yes

    - name: install pip
      become: yes
      easy_install:
          name: pip
          executable: "/usr/bin/easy_install-3"

    - name: Install python-virtualbmc with pip
      become: true
      pip:
          name: virtualbmc
          state: latest
  when: virtualbmc_install_result|failed
