- name: Ease iptables rules on hypervisor
  iptables:
      action: insert
      comment: "Infrared: vbmc ports"
      table: filter
      chain: FORWARD
      jump: ACCEPT
      protocol: "udp"
      destination_port: "{{ item.value }}"
  with_dict: "{{ vbmc_ports }}"
  delegate_to: hypervisor

- name: Ease iptables rules on vbmc host
  become: true
  iptables:
      action: insert
      comment: "Infrared: vbmc ports"
      table: filter
      chain: INPUT
      jump: ACCEPT
      protocol: "udp"
      destination_port: "{{ item.value }}"
  with_dict: "{{ vbmc_ports }}"

- name: Make created iptables rules persistant
  become: true
  shell: "/sbin/service iptables save"
