- name: config
  include_vars: "{{ playbook_dir }}/../config.yml"

- name: set stack1 name
  set_fact:
    rh_stack_name: "stack1"
  when: "rh_stack_name is not defined and 'stack1' in group_names"

- name: set stack2 name
  set_fact:
    rh_stack_name: "stack2"
  when: "rh_stack_name is not defined and 'stack2' in group_names"

- name: setup stack1-local variables
  set_fact:
    vbmc_nodes: "{{ groups.get('stack1_overcloud_nodes', groups.get('overcloud_nodes', [])) }}"
  when: "rh_stack_name == 'stack1'"

- name: setup stack2-local variables
  set_fact:
    vbmc_nodes: "{{ groups.get('stack2_overcloud_nodes', groups.get('overcloud_nodes', [])) }}"
  when: "rh_stack_name == 'stack2'"

- name: set hypervisor management address
  set_fact:
    management_ipv4_address: "{{ hostvars['hypervisor']['ansible_default_ipv4']['address'] }}"


- include_tasks: install.yml

- include_tasks: configure.yml

- name: Register vars for instackenv template
  set_fact:
      vbmc_ports: "{{ vbmc_ports }}"
      vbmc_management_address: "{{ vbmc_management_address }}"
