- name: config
  include_vars: "{{ playbook_dir }}/../config.yml"

- name: setup variables
  set_fact:
    vbmc_nodes: "{{ groups.get('overcloud_nodes', []) }}"

- name: set hypervisor management address
  set_fact:
    management_ipv4_address: "{{ hostvars['hypervisor']['ansible_default_ipv4']['address'] }}"


- include_tasks: install.yml

- include_tasks: configure.yml

