# in order to change parameters compared to the original mysql, copy
# the whole kolla config to a new one that can be modified.

- name: create all new kolla config
  shell: cp -R /var/lib/config-data/puppet-generated/mysql/ /var/lib/config-data/puppet-generated/mysql-stretch/
  become: true

- name: change galera.cnf
  ini_file:
    path: /var/lib/config-data/puppet-generated/mysql-stretch/etc/my.cnf.d/galera.cnf
    section: "{{ item['section'] }}"
    option: "{{ item['key'] }}"
    value: "{{ item['value'] }}"
    backup: yes
  become: true
  with_items:
    - {"section": "mysqld", "key": "port", "value": "{{ galera_listen_port }}"}
    - {"section": "client", "key": "port", "value": "{{ galera_listen_port }}"}
    - {"section": "mysqld", "key": "bind-address", "value": "{{ galera_bind_address }}"}

# NOTE: the file seems to use root, maybe we should not assume that
- name: set clustercheck password
  lineinfile:
    path: /var/lib/config-data/puppet-generated/mysql-stretch/etc/sysconfig/clustercheck
    regexp: "^MYSQL_PASSWORD=.*"
    line: "MYSQL_PASSWORD='{{ stretch_galera_root_password }}'"
  become: true

