- name: create host mysql dir
  file:
    path: /var/lib/mysql-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  register: created_data_directory
  become: true

- name: create host mysql log dir
  file:
    path: /var/log/containers/mysql-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  become: true

- name: create host mariadb log dir
  file:
    path: /var/log/mariadb-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  become: true

- name: set up volumes
  set_fact:
      galera_volumes:
        - {
            "id": "stretch-galera-mysql-log",
            "source": "/var/log/containers/mysql-stretch",
            "target": "/var/log/mysql",
            "flags": "rw"
          }
        - {
            "id": "stretch-galera-mariadb-log",
            "source": "/var/log/mariadb-stretch",
            "target": "/var/log/mariadb",
            "flags": "rw"
          }
        - {
            "id": "stretch-galera-mysql-lib",
            "source": "/var/lib/mysql-stretch",
            "target": "/var/lib/mysql",
            "flags": "rw"
          }
        - {
            "id": "stretch-galera-cfg-files",
            "source": "/var/lib/kolla/config_files/mysql.json",
            "target": "/var/lib/kolla/config_files/config.json",
            "flags": "ro"
          }
        - {
            "id": "stretch-galera-cfg-data",
            "source": "/var/lib/config-data/puppet-generated/mysql-stretch/",
            "target": "/var/lib/kolla/config_files/src",
            "flags": "ro"
          }
        - {
            "id": "stretch-galera-hosts",
            "source": "/etc/hosts",
            "target": "/etc/hosts",
            "flags": "ro"
          }
        - {
            "id": "stretch-galera-localtime",
            "source": "/etc/localtime",
            "target": "/etc/localtime",
            "flags": "ro"
          }
        - {
            "id": "stretch-galera-mysql-dev-log",
            "source": "/dev/log",
            "target": "/dev/log",
            "flags": "rw"
          }
        - {
            "id": "stretch-galera-root-ssh",
            "source": "/root/.ssh",
            "target": "/root/.ssh",
            "flags": "ro"
          }
        - {
            "id": "stretch-galera-setup-script",
            "source": "/tmp/stretch_galera_dockerbuild/",
            "target": "/setup",
            "flags": "ro"
          }

# assemble dictionary items into a list of strings. trivial in Python,
# impossible in jinja.  See three-year-old workaround:
# https://github.com/ansible/ansible/pull/8019#issuecomment-95480311
- name: render volume entries for docker
  set_fact: volume_string="{{ item['source'] }}:{{ item['target'] }}:{{ item['flags'] }}"
  with_items: "{{ galera_volumes }}"
  register: volume_string_result

- name: set container volumes fact
  set_fact:
      galera_docker_volumes: "{{ volume_string_result.results | map(attribute='ansible_facts.volume_string') | list }}"

- name: create setup mount
  file:
    path: /tmp/stretch_galera_dockerbuild
    state: directory

- name: copy setup script
  template:
    src: setup_stretch_database.sh
    dest: /tmp/stretch_galera_dockerbuild/setup_stretch_database.sh

- name: use the docker container to create mysql setup
  docker_container:
    name: stretch_galera_cmd
    cleanup: true
    image: "{{ stretch_galera_imagename }}"
    command: /setup/setup_stretch_database.sh
    volumes: "{{ galera_docker_volumes }}"
    network_mode: host
    detach: false
  become: true


- name: copy resource agent to controller
  copy:
    src: galera_ra.sh
    dest: /usr/lib/ocf/resource.d/heartbeat/galera
    mode: 0755
    owner: root
    group: root
  become: true

- name: set stretch-galera-role for pacemaker node
  shell: /usr/sbin/pcs node attribute {{ pacemaker_node_name }} stretch-galera-role=true
  become: true



