- name: create image
  include_tasks: create_docker_image.yml

- name: setup mysql directories and parameters
  include_tasks: init_mysql.yml

- name: run iptables config
  include_tasks: setup_iptables.yml

- name: run galera via docker
  include_tasks: run_container_directly.yml
  when:
    deploy_via_pacemaker|bool == false

- name: run galera via pacemaker
  block:
    - include_tasks: create_kolla_config.yml
    - include_tasks: add_pacemaker_resource.yml
  when:
    deploy_via_pacemaker|bool == true

- name: wait for it to run
  shell: docker exec {{ container_name }} mysql -u root --password="{{ stretch_galera_root_password }}" -s --skip-column-names -e "show status like 'wsrep_local_state'"
  register: result
  until: result.stdout.find("4") != -1
  retries: 20
  delay: 5
  become: true
  any_errors_fatal: true
  run_once: true

- name: set up a root user that can get there from the network
  shell: docker exec {{ container_name }} mysql -u root --password="{{ stretch_galera_root_password }}" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ stretch_galera_root_password }}' WITH GRANT OPTION"
  become: true
  run_once: true
