
- name: setup kolla config and config variables
  include_tasks: create_kolla_config.yml

- name: create image
  include_tasks: create_docker_image.yml

- name: setup mysql directories and parameters
  include_tasks: init_mysql.yml

- name: run iptables config
  include_tasks: setup_iptables.yml

- name: run galera via pacemaker
  include_tasks: add_pacemaker_resource.yml
  when:  "'pacemaker_control_nodes' in group_names"

- name: get docker container name
  shell: "docker ps | grep stretch-galera-bundle-docker | awk -F' ' '{print $NF}'"
  register: docker_ps_cmd
  become: true
  retries: 5
  delay: 5
  any_errors_fatal: true
  run_once: true

- name: wait for galera to be available
  shell: docker exec {{ docker_ps_cmd.stdout_lines[0] }} mysql -u root --password="{{ galera_root_password }}" -s --skip-column-names -e "show status like 'wsrep_local_state'"
  register: result
  until: result.stdout.find("4") != -1
  retries: 20
  delay: 5
  become: true
  any_errors_fatal: true
  run_once: true

- name: set up a root user that can get there from the network
  shell: docker exec {{ docker_ps_cmd.stdout_lines[0] }} mysql -u root --password="{{ galera_root_password }}" -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '{{ galera_root_password }}' WITH GRANT OPTION"
  become: true
  run_once: true
