- name: create image
  include_tasks: create_docker_image.yml

- name: create host mysql dir
  file:
    path: /var/lib/mysql-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  register: created_data_directory
  become: true

- name: create host mysql log dir
  file:
    path: /var/log/containers/mysql-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  become: true

- name: create host mariadb log dir
  file:
    path: /var/log/mariadb-stretch
    state: directory
    owner: "{{ mysql_uid }}"
    group: "{{ mysql_gid }}"
  become: true

- name: set container volumes fact
  set_fact:
      galera_volumes:
        - /var/log/containers/mysql-stretch:/var/log/mysql
        - /var/log/mariadb-stretch:/var/log/mariadb
        - /etc/hosts:/etc/hosts:ro
        - /var/lib/mysql-stretch:/var/lib/mysql:rw
        - /etc/localtime:/etc/localtime:ro
        - /dev/log:/dev/log:rw
        - /etc/pacemaker/authkey:/etc/pacemaker/authkey
        - /var/lib/kolla/config_files/mysql.json:/var/lib/kolla/config_files/config.json:ro
        - /var/lib/config-data/puppet-generated/mysql/:/var/lib/kolla/config_files/src:ro
        - /root/.ssh:/root/.ssh

- name: create mysql setup
  docker_container:
    name: stretch_galera_cmd
    cleanup: true
    image: "{{ stretch_galera_imagename }}"
    command: /bin/mysql_install_db --datadir=/var/lib/mysql --user=mysql
    volumes: "{{ galera_volumes }}"
    network_mode: host
    detach: false
  become: true
  when: created_data_directory.changed

# TODO: simple single master / single follower setup to start with.  we
# later would want this to be a little more open ended

- name: create gcomm address
  set_fact:
      gcomm_address: "gcomm://{{ master_ip }},{{ follower_ip }}"

- name: set master parameters
  set_fact:
      galera_parameters: >
          --bind-address={{ master_ip }}
          {{ deploy_via_pacemaker|bool==false | ternary("--wsrep-new-cluster", "") }}
          --wsrep-provider-options=gmcast.listen_addr=tcp://{{ master_ip }}:4567;pc.weight=2
          --wsrep-sst-receive-address={{ master_ip }}
      cluster_host_map: "stack1-overcloud-controller-0:{{ master_ip }};stack2-overcloud-controller-0:root@{{ follower_ip }}"

  when: inventory_hostname == "{{ galera_master_inventoryname }}"

- name: set follower parameters
  set_fact:
      galera_parameters: >
        --bind-address={{ follower_ip }}
        --wsrep-provider-options=gmcast.listen_addr=tcp://{{ follower_ip }}:4567;pc.weight=1
        --wsrep-sst-receive-address={{ follower_ip }}
      cluster_host_map: "stack1-overcloud-controller-0:root@{{ master_ip }};stack2-overcloud-controller-0:{{ follower_ip }}"
  when: inventory_hostname != "{{ galera_master_inventoryname }}"

- name: open up iptables rule
  lineinfile:
    path: /etc/sysconfig/iptables
    insertafter: "-A INPUT .* 3306 .* -j ACCEPT"
    line: '-A INPUT -p tcp -m multiport --dports 3307 -m state --state NEW -m comment --comment "100 mysql_stretch_haproxy ipv4" -j ACCEPT'
  notify: reload iptables
  become: true

- name: open up iptables rule
  lineinfile:
    path: /etc/sysconfig/iptables
    insertafter: "-A INPUT .* 3306 .* -j ACCEPT"
    line: '-A INPUT -p tcp -m multiport --dports {{ pacemaker_network_control_port }} -m state --state NEW -m comment --comment "100 mysql_stretch_haproxy ipv4" -j ACCEPT'
  notify: reload iptables
  become: true

- name: ensure restart happens
  meta: flush_handlers

- name: run galera via docker
  include_tasks: run_container_directly.yml
  when:
    deploy_via_pacemaker|bool == false


- name: run galera via pacemaker
  include_tasks: add_pacemaker_resource.yml
  when:
    deploy_via_pacemaker|bool == true

- name: wait for it to run
  shell: docker exec stretch_galera mysql -u root -s --skip-column-names -e "show status like 'wsrep_local_state'"
  register: result
  until: result.stdout.find("4") != -1
  retries: 5
  delay: 5
  become: true
  any_errors_fatal: true

# stretch-galera-bundle
# stretch_galera

- name: set up a root user that can get there from the network
  shell: docker exec {{ container_name }} mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root' WITH GRANT OPTION"
  become: true

