- name: open up iptables rule
  lineinfile:
    path: /etc/sysconfig/iptables
    insertafter: "-A INPUT .* 3306 .* -j ACCEPT"
    line: '-A INPUT -p tcp -m multiport --dports {{ stretch_galera_listen_port }} -m state --state NEW -m comment --comment "100 mysql_stretch_haproxy ipv4" -j ACCEPT'
  notify: reload iptables
  become: true

- name: open up iptables rule
  lineinfile:
    path: /etc/sysconfig/iptables
    insertafter: "-A INPUT .* 3306 .* -j ACCEPT"
    line: '-A INPUT -p tcp -m multiport --dports {{ pacemaker_network_control_port }} -m state --state NEW -m comment --comment "100 mysql stretch-galera-bundle ipv4" -j ACCEPT'
  notify: reload iptables
  become: true

- name: ensure restart happens
  meta: flush_handlers

