
- name: copy prep network script
  template:
    src: "overcloud-prep-network.sh.j2"
    dest: "{{ working_dir }}/overcloud-prep-network.sh"
    mode: 0755

- name: run prep network script
  shell: >
    set -o pipefail &&
    {{ working_dir }}/overcloud-prep-network.sh 2>&1 > overcloud_prep_network.log
