- name: Gather facts for Hypervisor and undercloud
  hosts: hypervisor, undercloud
  gather_facts: yes
  any_errors_fatal: true


- name: setup vbmc
  hosts: undercloud
  gather_facts: false
  roles:
    - {role: vbmc, tags: ['setup_vbmc'] }
