---

- name: deploy galera
  hosts: galera_nodes
  roles:
     - { role: gather-info, tags: ['always'] }
     - { role: run-galera-containers, tags: ['run_galera'] }
     - { role: run-clustercheck, tags: ['run_clustercheck'] }

- name: setup pacemaker 
  hosts: pacemaker_control_nodes
  roles:
    - setup-pacemaker
  tags:
    - setup_pacemaker
