---

- name: get galera node facts
  hosts: galera_nodes
  roles:
    - gather-info
  tags:
    - always

- name: Run galera on the two hosts
  hosts: galera_nodes
  roles:
    - run-galera-containers
  tags:
    - run_galera

- name: install clustercheck
  hosts: galera_nodes
  roles:
    - run-clustercheck
  tags:
    - run_clustercheck
