- name: Gather facts for Hypervisor
  hosts: hypervisor
  gather_facts: yes
  any_errors_fatal: true

- name: prep and deploy overcloud
  hosts: undercloud
  gather_facts: yes
  roles:
    - {role: hack-tripleo, tags: ['hack-tripleo']}
    - deploy-overcloud

