- name: Gather facts for Hypervisor
  hosts: hypervisor
  gather_facts: yes
  any_errors_fatal: true

- name: prep and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - deploy-overcloud

