- name: Gather facts for Hypervisor and undercloud
  hosts: hypervisor, undercloud
  gather_facts: yes
  any_errors_fatal: true

- name: generate ssh key
  hosts: hypervisor
  gather_facts: no
  roles:
    - {role: gen-ssh-key, tags: ['gen_ssh_key']}

- name: prep and deploy overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - {role: add-undercloud-routes, tags: ['setup_routes'] }
    - {role: deploy-overcloud, tags: ['deploy_overcloud']}


