---

- name: gather info
  hosts:
    - stack1
    - stack2
  gather_facts: no
  roles:
     - { role: gather-info, tags: ['always'] }

- name: setup region name in openstack services (tripleo should do this)
  hosts:
    - stack1_controller
    - stack2_controller
  gather_facts: no
  roles:
    - { role: setup-openstack-services, tags: ['setup_openstack_services']}


