---

- name: gather info
  hosts:
    - stack1
    - stack2
  roles:
     - { role: gather-info, tags: ['always'] }

- name: setup undercloud routes
  hosts:
    - undercloud
  gather_facts: no
  roles:
    - { role: add-undercloud-routes, tags: ['setup_routes'] }

- name: deploy galera
  hosts: galera_nodes
  gather_facts: no
  roles:
     - { role: run-galera-containers, tags: ['run_galera'] }
     - { role: run-clustercheck, tags: ['run_clustercheck'] }

- name: point openstack at galera
  hosts:
    - stack1_controller
    - stack2_controller
  gather_facts: no
  roles:
     - { role: setup-pacemaker, tags: ['setup_pacemaker'] }
     - { role: setup-haproxy, tags: ['setup_haproxy'] }

- name: setup keystone data
  hosts:
    - galera_nodes
  gather_facts: no
  roles:
    - { role: setup-keystone-db, tags: ['setup_keystone_db'] }


- name: point keystone services to the new galera DB
  hosts:
    - stack1_controller
    - stack2_controller
  gather_facts: no
  roles:
    - { role: setup-openstack-services, tags: ['setup_openstack_services'] }

